### ISSUE TITLE
New feature: `Placement` "middle"

### ISSUE THREAD

**Issue by monsieurtanuki** [ookami-kb/flutter_arc_text#10]
For the record, during the development of my app I've just found out that I was better off with a new `Placement` value: `middle`. And I also use the following parameters in order to have a very good top/bottom match with the texts on both `Direction` at the same time:
```dart
TextStyle(
  textBaseline: TextBaseline.ideographic,
  height: 1,
)
```

That's not 100% related, but I've also built classes in order to have `flutter_arc_text` work not only on `Canvas`, but also on [`html.CanvasRenderingContext2D`](https://api.flutter.dev/flutter/dart-html/CanvasRenderingContext2D-class.html). Not sure if many people would be interested by that.

**Comment by ookami-kb** [comment]
Yeah, `Placement.middle` sounds good! 👍 

If you can create a PR with that, it would be great.

**Comment by monsieurtanuki** [comment]
Hi @ookami-kb 
Again I'm in a GitHub trap and for the amount of changes involved it wouldn't be worth it. Besides, you'll have to deal with a new demo and pub.dev delivery anyway.

I guess the change would be something like:
```dart
enum Placement { inside, outside, middle }
```
in `enums.dart`

and
```dart
switch (placement) {
  case Placement.inside:
    this._radius = radius - _textPainter.height;
    break;
  case Placement.outside:
    this._radius = radius;
    break;
  case Placement.middle:
    this._radius = radius - _textPainter.height / 2;
    break;
}
```
in `art_text_painter.dart`

**Comment by ookami-kb** [comment]
Thanks! Added to `0.3.2`.
