### ISSUE TITLE
Decoration support

### ISSUE THREAD

**Issue by aytunch** [ookami-kb/flutter_arc_text#18]
I would like to have a background container along with the arc text which have rounded corners. And with a gradient bg color. For the time being it seems impossible to do.

However this is very important to use over images since image might be same color with the text so we need something behind the text.

What do you think @ookami-kb @monsieurtanuki ?

**Comment by ookami-kb** [comment]
If you mean something like this:

![image](https://user-images.githubusercontent.com/853356/120180520-24ef7100-c20c-11eb-9733-5638fa933bd2.png)

It's possible using `PainterDelegate`. Check [this method](https://github.com/ookami-kb/flutter_arc_text/blob/master/packages/flutter_arc_text/example/lib/main.dart#L101) in example for more details (especially, `hasBackground` property).

**Comment by aytunch** [comment]
This is exactly what I was looking for,
Thanks a lot. I will be trying to customize the bg label to my needs. I am closing the issue now. If I have question I will write again.
Superb:)
