### ISSUE TITLE
anti-clockwise, static function, length computation

### ISSUE THREAD

**Issue by monsieurtanuki** [ookami-kb/flutter_arc_text#2]
Very useful code, thank you!

I'm currently porting an Android/java app to flutter; I have some needs/suggestions, that I will have to implement and may integrate into this project (if you're OK with that):
1. being able to write text anti-clockwise
1. calling the code from any `CustomPainter` (which may mean moving the code into a `static` function or tool class)
1. adding some `length()` tools - I have no control on the text, which means I need to check if it fits in this circle (if not, I use a smaller font size for instance)

**Comment by ookami-kb** [comment]
Thank you!

Yeah, sounds good. If you're ok to create them as separate PRs that would be great.

1. 👍 
2. I guess `_Painter` can be made a public class and passed as a default parameter to `ArcText`, so you can substitute it with your own implementation extending this class.
3. Maybe `_getFinalAngle` will help here if it will be public/protected – if the final angle is greater than 360° it means that text doesn't fit.

**Comment by monsieurtanuki** [comment]
Cool!
1. Working on it...
1. I guess we'll also have to add parameters like `Offset` for the circle center. I've just started developing in flutter and I don't know the best practices performance-wise and code reusability-wise.
1. I was thinking about that too
1. [new suggestion] - `TextDirection.ltr` could be a parameter too

**Comment by ookami-kb** [comment]
Yeah, `textDirection` can be taken into account to get the general direction in the widget. At least I can't think about any other use case for implementing anti-clockwise direction. In that case we can internally use `Directionality.of` method to get the default one. Or do you have some specific case in mind?

Regarding offset parameter – I'm not sure what's the use case for it, as you can just re-position the widget itself. Or do you know some?

**Comment by monsieurtanuki** [comment]
I was just wondering if it made sense to give the users the ability to use something else than leftToRight. But I don't have a strong interest on that subject for the moment.

Regarding offset parameter, my point is that I don't care about widgets (I've just started flutter, remember?).
My use case is displaying a large canvas with many things, including an arc text. And I need to export the "screenshot" as a .JPG file, therefore I cannot just stack widgets, at one time I need to be able to draw everything on a canvas that is not centered on the arc text.

**Comment by ookami-kb** [comment]
> at one time I need to be able to draw everything on a canvas that is not centered on the arc text.

I see. So I guess smth like this can do the trick, without adding the parameter:

```dart
// Let's say we've made _Painter a public class:    
final arcTextPainter = ArcTextPainter();

// somewhere in general paint method
canvas.save();
canvas.translate(dx, dy);
arcTextPainter.paint(canvas, size);
canvas.restore();
```

**Comment by monsieurtanuki** [comment]
I'm not sure, perhaps we would have to involve `size` in the `translate` code line too.
Anyway we'll see that later: first, anti-clockwise mode.

**Comment by monsieurtanuki** [comment]
I've just sent PR #3 regarding the anti-clockwise feature.

About the `static` vs. `CustomPainter` controversy, I think a good idea would be to get inspiration from what currently exists in flutter, like [`TextPainter`](https://api.flutter.dev/flutter/painting/TextPainter-class.html) (that does not implement `CustomPainter`).
What do you think? And I agree, `ArcTextPainter` seems appropriate.

**Comment by monsieurtanuki** [comment]
I've also just developed a new feature: `bool outside = true` - if false the letters are displayed _inside_ the circle, not outside. Tell me if you're interested.

**Comment by ookami-kb** [comment]
Hey, I've added some notes to your PR.

Regarding making `ArcTextPainter` independent from `CustomPainter` – yeah, I think it can be useful, so it can be reused somewhere else in the code. 

And together with a widget, it can be used in some `CustomPainter` that will delegate `paint` method to `ArcTextPainter`.

**Comment by monsieurtanuki** [comment]
Excellent! OK for an independent `ArcTextPainter` and for your PR change suggestions.
What's the next step? I don't mind if you continue the coding, I don't mind if I continue the coding.
If you continue, remember that I need a "string-angle-length" method (and I won't be the only one interested in it). Something like that in `ArcTextPainter`:
```dart
static double getRotation(final String text, TextPainter textPainter,
    TextStyle textStyle, double radius) {
  double finalRotation = 0;
  for (int i = 0; i < text.length; i++) {
    finalRotation += _getRotation(text[i], textPainter, textStyle, radius);
  }
  return finalRotation;
}
```

**Comment by ookami-kb** [comment]
Nice! In that case please merge my patch into your PR, I will merge it into the master and will create another PR with extracting `ArcTextPainter`.

**Comment by monsieurtanuki** [comment]
Erm, how can I merge your patch, I can only see a formatted text but no github commit on top of mine. You meant, like copy-pasting?

**Comment by ookami-kb** [comment]
You can copy the entire `patch` snippet, and then, if you're using Android Studio or IntelliJ Idea, you can use the menu item `VCS → Apply Patch from Clipboard...`

**Comment by monsieurtanuki** [comment]
Done. Thanks for the tip!

**Comment by ookami-kb** [comment]
Hey, I've published a new version with all the changes and extracted `ArcTextPainter` as we discussed with `getFinalAngle` method: https://pub.dev/documentation/flutter_arc_text/latest/flutter_arc_text/ArcTextPainter-class.html

**Comment by monsieurtanuki** [comment]
I've just replaced in my app my custom code with `flutter_arc_text: ^0.2.0` and everything works fine!

My only regret: I really don't think that makes sense to use `Size` in `void paint(Canvas canvas, Size size)`. I had more `void paint(Canvas canvas, Offset center)` in mind, like in the "regular" `TextPainter`.
`Size` would have mades sense for a `CustomPainter`, which `ArcTextPainter` is not.

Very good screenshot in the README section.

Thanks for the good job!

**Comment by ookami-kb** [comment]
Hey, so maybe it should just be method `void paint(Canvas canvas)`, so that you move the Canvas to the needed position yourself in your calling code?

**Comment by monsieurtanuki** [comment]
* My opinion is rather `paint(Canvas, Offset)`: "I want to paint an arc text centered here". I'm able to explain the meaning of the parameters. And it's similar to the standard `TextPainter` (when I'm stuck with a metaphysical question about UX, I ask myself: "how do other people do?")
* Asking the user to use `canvas.save`, `canvas.translate` and `canvas.restore` is not very user-friendly.
* The `Size` is hard to explain (not related to radius, nothing to do with an ellipse either), and is there only for legacy reason regarding the initial `ArcText` extending `CustomPainter`. And that brings confusion too: "there's a `paint(Canvas, Size)` method but it does not extends `CustomPainter`- what is it exactly?"

That being said, now I'm able to do everything I talked about initially and even more (inside/outside). That's good!
It's just that the `Size` parameter is not intuitive. Maybe it's just a matter of opinion and there's no perfect answer.

**Comment by ookami-kb** [comment]
Yeah, I agree that `Size` parameter is confusing.

>  rather paint(Canvas, Offset): "I want to paint an arc text centered here". I'm able to explain the meaning of the parameters. 

Fair point. I've updated the `paint` method signature to accept `Offset`, so it's a small breaking change in a new version, as Dart, unfortunately, doesn't support method overloading.

**Comment by monsieurtanuki** [comment]
Cool, it's much better that way.
And the only users potentially negatively impacted by the change from `Size` to `Offset` would only be whoever downloaded the new version yesterday and specifically used `ArcTextPainter` and not just `ArcText`.
By curiosity, do you have the number of downloads? I'm not asking for the actual number: do they provide you with stats regarding downloads and so on?

**Comment by ookami-kb** [comment]
No, no stats at all, only this relative "Popularity" score, which is publicly accessible: https://pub.dev/packages/flutter_arc_text#-analysis-tab-

**Comment by monsieurtanuki** [comment]
We're all set, then.
Thanks for the good job, and if I have another idea about arc text I'll create a new issue.
Bye!
