### ISSUE TITLE
Use DefaultTextStyle, if textStyle is not supplied

### ISSUE THREAD

**Issue by bramp** [ookami-kb/flutter_arc_text#22]
The standard flutter `Text` widget, does not require a `textStyle`, and instead uses the closest enclosing `DefaultTextStyle`.

It would be convenient to make textStyle optional in the `ArcText`, and follow the same behaviour as the `Text` widget.

Happy to send a PR if you think its reasonable. Thanks.

**Comment by ookami-kb** [comment]
Hey, yep, sounds good. If you could submit a PR that would be awesome!
