### ISSUE TITLE
New feature for text stretching

### ISSUE THREAD

**Issue by monsieurtanuki** [ookami-kb/flutter_arc_text#4]
I've just developed a very useful feature: a `double interLetterSpacing = 0` parameter in the `ArcTextPainter` constructor.

The idea behind that is:
1. I've got a text to display around a circle
1. I compute the "final angle", let's say it's `pi`
1. If I display the text as is, it's going to be displayed on a `pi` angle, fair enough
1. But I would like the text to stretch to the whole `2*pi` angle
1. The idea is to rotate an extra angle for each letter - hence the extra parameter in the constructor

Computing the extra angle is my own business so far (something like `(2*pi - getFinalAngle()) / text.length`), though it could also be included in the library (like a `bool autoStretch = false` parameter in the constructor).
But the thing absolutely needed is the support of this `double interLetterSpacing = 0` parameter in the `ArcTextPainter` constructor.

What do you think about that?

**Comment by monsieurtanuki** [comment]
Would you like me to send a PR?

**Comment by ookami-kb** [comment]
Hey, `ArcTextPainter` and `ArcText` take `TextStyle` as a parameter, so you can set `letterSpacing` in the `TextStyle`.

**Comment by monsieurtanuki** [comment]
I don't believe this would work, as we're drawing letter by letter. No spacing between letters involved, then. As far as I understand TextStyle's letterSpacing.

**Comment by ookami-kb** [comment]
It works.

**Comment by monsieurtanuki** [comment]
I'm not entirely convinced, and I'll tell you why later. For the moment I'm stuck in a github nightmare.

**Comment by monsieurtanuki** [comment]
Actually you're right, it does work. But...

If I take this example, I just use the standard arc_text_painter feature:
<img width="230" alt="Screenshot_2020-05-25-17-43-36" src="https://user-images.githubusercontent.com/11576431/82827697-d1876c00-9eaf-11ea-9879-25ad7e9d3390.png">

But just by adding a parameter in my call, like a new `autoStretch: 2*math.pi`, I could get an immediate good result without having to tap dance with the text letter spacing parameter:
<img width="228" alt="Screenshot_2020-05-25-17-43-24" src="https://user-images.githubusercontent.com/11576431/82827827-11e6ea00-9eb0-11ea-9851-666cba648f3c.png">

What do you think of that?

**Comment by ookami-kb** [comment]
Sounds good 👍

**Comment by monsieurtanuki** [comment]
I should be able to send a PR by the end of the week.

**Comment by ookami-kb** [comment]
Fixed in #9
